services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Garlic\Gateway\Service\:
        resource: '../../Service/*'
    Garlic\Gateway\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
    # Convert all errors to JSON format
    base.exception_subscriber:
        class: App\EventSubscriber\ExceptionSubscriber
        tags:
            - { name: kernel.event_subscriber }

    gateway.command.health_check:
        public: true
        alias: 'Garlic\Gateway\Command\HealthCheckHeartBeatCommand'

    Garlic\Gateway\Command\HealthCheckHeartBeatCommand:
        class: 'Garlic\Gateway\Command\HealthCheckHeartBeatCommand'
        public: true
        tags:
            - { name: 'console.command' }